/*
* generated by Xtext
*/
package bg.tues;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DidiUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return bg.tues.ui.internal.DidiActivator.getInstance().getInjector("bg.tues.Didi");
	}
	
}
