/**
 * generated by Xtext
 */
package bg.tues.ui.contentassist;

import bg.tues.ui.contentassist.AbstractDidiProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DidiProposalProvider extends AbstractDidiProposalProvider {
}
