/**
 * generated by Xtext
 */
package org.ui.contentassist;

import org.ui.contentassist.AbstractDataCentricDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DataCentricDSLProposalProvider extends AbstractDataCentricDSLProposalProvider {
}
