/*
* generated by Xtext
*/
package org.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.services.DataCentricDSLGrammarAccess;

public class DataCentricDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DataCentricDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.parser.antlr.internal.InternalDataCentricDSLParser createParser(XtextTokenStream stream) {
		return new org.parser.antlr.internal.InternalDataCentricDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DataCentricDSL";
	}
	
	public DataCentricDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DataCentricDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
