/*
 * generated by Xtext
 */
package bg.tues.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import bg.tues.ui.internal.DidiActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DidiExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DidiActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DidiActivator.getInstance().getInjector(DidiActivator.BG_TUES_DIDI);
	}
	
}
