/*
 * generated by Xtext
 */
package bg.tues.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DidiUiModule extends bg.tues.ui.AbstractDidiUiModule {
	public DidiUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
