/*
 * generated by Xtext
 */
package bg.tues.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import bg.tues.services.DidiGrammarAccess;

public class DidiParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DidiGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected bg.tues.parser.antlr.internal.InternalDidiParser createParser(XtextTokenStream stream) {
		return new bg.tues.parser.antlr.internal.InternalDidiParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DidiModel";
	}
	
	public DidiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DidiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
