/*
* generated by Xtext
*/
package org;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DataCentricDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ui.internal.DataCentricDSLActivator.getInstance().getInjector("org.DataCentricDSL");
	}
	
}
