
for(;;){
	
}

*/
if(1 == 1){
	global a = 0;
}

println a;
*/
/*
for(i = 0; i < 5; i = i + 1){
	println i;
}

for(i = 10; i > 0; i--){
	println i;
}
*/
/*
func asd(a){
	println query a;
}

a = "SELECT * FROM people";
asd(a);
*/
/*
func compareNumbers(a,b){
	if(a == b){
		println "a == b";
	}else{
		println"a != b";
	}
}

compareNumbers(1,1);
println "";

for(i = 0; i < 5; i = i + 1){
	println i;
}


a = "SELECT * FROM people";
b = query a;
println b;

*/
/*
func hello(a,b){
	if(a == b){
		println a + " = " + b;
	}else{
		println "damn...";
	}
}


hello(1,1);


a = 0;
a++;
println a;
*/
/*

for(a = 0; a < 5; a = a + 1){
	if(a == 1){
		println a;
	}
}
*/


/*
for(b = 0; b < 5){
	println b;
}
*/
/*
a = "SELECT first_name FROM people";
b = query a;
println b;
*/
/*
a = 1;
while(a < 10){
	println a;
	a = a + 1;
}
*/

/*
a = "a";
b = "b";

c = query "SELECT * FROM people";
println c;

a = 0;
if(a == 2){
	println "YES";
}else if(a > 5){
	println "a > 5";
}else{
	println "NO";
}

println query "SELECT * FROM people";
*/