def hello()
	println("Hello World");
end

hello();

/*
a = 0;
a++;
println(a);
*/
/*
for(a = 0; a < 5; a = a + 1){
	if(a == 1){
		println(a);
	}
}
*/
/*
for(a = 0; a < 5){
	//println(a);
}

println(a);
*/
/*
for(b = 0; b < 5){
	println(b);
}
*/
/*
a = "SELECT first_name FROM people";
b = query a;
println(b);
*/
/*
a = 1;
while(a < 10){
	println(a);
	a = a + 1;
}
*/

/*
a = "a";
b = "b";

c = query "SELECT * FROM people";
println(c);

a = 0;
if(a == 2){
	println("YES");
}else if(a > 5){
	println("a > 5");
}else{
	println("NO");
}

println query "SELECT * FROM people";
*/
/*
a = 2;
if a < 10 do
	println("YES");
else do
	println("NO");
end
println(a);

b = query "SELECT * FROM people";
println(b);
*/

/*
a = 5;

if a < 4 do
  a = 1;
else if a < 0 do 
  a = 2;
else do
  a = 42;
end

println(a);
*/
