/*
 * generated by Xtext
 */
package bg.tues;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DidiRuntimeModule extends bg.tues.AbstractDidiRuntimeModule {

}
