/*
* generated by Xtext
*/
package bg.tues;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DidiStandaloneSetup extends DidiStandaloneSetupGenerated{

	public static void doSetup() {
		new DidiStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

