/*
* generated by Xtext
*/
package org;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DataCentricDSLStandaloneSetup extends DataCentricDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new DataCentricDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

