/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DataCentricDSLUiModule extends org.ui.AbstractDataCentricDSLUiModule {
	public DataCentricDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
